// Custom addition to the next-pwa generated service worker (bundled in via
// next-pwa's customWorkerDir convention — see README.md → "Custom Worker").
// Handles practice-reminder push notifications only; precaching/offline
// support is still entirely generated by workbox.

self.addEventListener('push', (event) => {
  let data = {};
  try {
    data = event.data ? event.data.json() : {};
  } catch {
    /* non-JSON payload — fall back to defaults below */
  }

  const title = data.title || 'Fluenta';
  const options = {
    body: data.body || 'Time for a bit of Spanish practice.',
    data: { url: data.url || '/lessons' },
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = event.notification.data?.url || '/lessons';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if (client.url.includes(url) && 'focus' in client) return client.focus();
      }
      if (self.clients.openWindow) return self.clients.openWindow(url);
    })
  );
});
