/**
 * Builds the service worker.
 *
 * This replaces next-pwa, which was generating a worker that installed and
 * then immediately went "redundant" — it threw during install, so there were
 * zero registrations, zero caches, and the app was completely dead offline
 * despite advertising itself as a PWA. next-pwa's last release was 2022 and
 * it has never properly supported the App Router; its auto-registration
 * targets a Pages Router entry point this app doesn't produce.
 *
 * Offline matters more here than for most apps: the whole point of a language
 * app is the ten minutes on a commute, and the Underground has no signal. It's
 * also achievable almost for free, because everything a lesson needs — the
 * curriculum, the readings, the exercise engine — is already bundled JS, and
 * progress already lives in localStorage. Caching the shell and the chunks is
 * genuinely all it takes.
 *
 * Run after `next build`, so the real hashed filenames exist to precache.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const NEXT_DIR = path.join(ROOT, '.next');
const PUBLIC = path.join(ROOT, 'public');

/** Every file under a directory, as web paths. */
function walk(dir, base) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    return e.isDirectory() ? walk(full, base) : [path.posix.join(base, path.relative(dir, full).split(path.sep).join('/'))];
  });
}

// The JS/CSS the app actually boots from. Hashed, so they're immutable and
// safe to cache forever.
const buildAssets = [
  ...walk(path.join(NEXT_DIR, 'static', 'chunks'), '/_next/static/chunks'),
  ...walk(path.join(NEXT_DIR, 'static', 'css'), '/_next/static/css'),
  ...walk(path.join(NEXT_DIR, 'static', 'media'), '/_next/static/media'),
].filter((p) => !p.endsWith('.map'));

// Icons and the manifest — needed for the installed app to look right offline.
const publicAssets = [
  '/manifest.json',
  ...walk(path.join(PUBLIC, 'icons'), '/icons'),
];

/**
 * The routes worth having offline. Deliberately not /tutor: a live voice call
 * needs the network by definition, and pretending otherwise would be worse
 * than an honest "you're offline".
 */
const ROUTES = ['/', '/lessons', '/practice', '/practice/listen', '/read', '/account', '/offline'];

/**
 * Only a small, guaranteed-fast set is fetched during install.
 *
 * The first version of this precached all 62 build assets and routes in one
 * Promise.all, and install simply never finished — it sat in "installing"
 * forever, so the worker never activated and never controlled a page. Dozens
 * of parallel fetches against a cold server, competing with the page's own
 * load, is not something install should be betting on.
 *
 * Everything else caches on first use instead (see the fetch handler), which
 * also matches how the app is really used: you open it at home on wifi, then
 * you're on the Underground. By the time offline matters, the chunks and
 * pages you touched are already there.
 */
const CRITICAL = ['/offline', '/manifest.json', ...walk(path.join(PUBLIC, 'icons'), '/icons')];

// Recorded in the worker purely so a future version can reason about the
// build it shipped with; not fetched at install time.
const PRECACHE = [...new Set([...buildAssets, ...publicAssets])];

const sw = `/**
 * GENERATED by scripts/build-sw.js — do not edit by hand.
 * Built ${new Date().toISOString()}
 */
const VERSION = 'fluenta-v${Date.now()}';
// Fetched during install — small and fast on purpose.
const CRITICAL = ${JSON.stringify(CRITICAL, null, 2)};
// The routes worth keeping once they've been visited.
const ROUTES = ${JSON.stringify(ROUTES)};

/** A fetch that can't hang install forever. */
async function fetchWithTimeout(url, ms) {
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), ms);
  try {
    return await fetch(url, { signal: controller.signal });
  } finally {
    clearTimeout(t);
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(VERSION);
      // Individually, tolerating failures — addAll() rejects the whole batch
      // if any single request fails, which is how the previous worker died.
      await Promise.all(
        CRITICAL.map(async (url) => {
          try {
            const res = await fetchWithTimeout(url, 5000);
            if (res.ok) await cache.put(url, res);
          } catch {
            // A missing icon must never stop the worker activating.
          }
        })
      );
      await self.skipWaiting();
    })()
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((n) => n !== VERSION).map((n) => caches.delete(n)));
      await self.clients.claim();
    })()
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

const isAsset = (url) =>
  url.pathname.startsWith('/_next/static/') ||
  url.pathname.startsWith('/icons/') ||
  url.pathname === '/manifest.json';

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // NEVER cache the API. Learner state is per-account and a stale or
  // cross-account response is far worse than an honest network error —
  // progress is already held in localStorage, so offline reads don't need it.
  if (url.pathname.startsWith('/api/')) return;

  // Hashed build output is immutable: cache-first, and it never goes stale.
  if (isAsset(url)) {
    event.respondWith(
      caches.match(request).then(
        (hit) =>
          hit ||
          fetch(request).then((res) => {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(request, copy)).catch(() => {});
            return res;
          })
      )
    );
    return;
  }

  // Pages: network-first so a connected learner always gets the current
  // build, with the cache as the fallback that makes a commute work. Every
  // successful navigation is cached, so visiting a page once online is what
  // makes it available offline later.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          const res = await fetch(request);
          if (res.ok && ROUTES.includes(new URL(request.url).pathname)) {
            const copy = res.clone();
            caches.open(VERSION).then((c) => c.put(request, copy)).catch(() => {});
          }
          return res;
        } catch {
          const hit = await caches.match(request);
          if (hit) return hit;
          // An unvisited route while offline — say so properly rather than
          // showing the browser's dinosaur.
          const offline = await caches.match('/offline');
          if (offline) return offline;
          return new Response('<h1>Offline</h1>', {
            status: 503,
            headers: { 'Content-Type': 'text/html' },
          });
        }
      })()
    );
  }
});
`;

fs.writeFileSync(path.join(PUBLIC, 'sw.js'), sw);

// next-pwa's leftovers would otherwise sit in public/ being served forever.
for (const stale of fs.readdirSync(PUBLIC)) {
  if (/^(workbox-|worker-)/.test(stale)) fs.unlinkSync(path.join(PUBLIC, stale));
}

console.log(
  `service worker written: ${PRECACHE.length} assets + ${ROUTES.length} routes precached`
);
