/**
 * The service worker is generated by scripts/build-sw.js, so what's testable
 * without a browser is the generator's output — specifically the properties
 * that would be dangerous or embarrassing to get wrong.
 *
 * Worth guarding because the previous worker (next-pwa's) installed and then
 * went straight to "redundant": zero caches, nothing worked offline, and
 * nothing anywhere said so.
 */
import { execFileSync } from 'child_process';
import fs from 'fs';
import path from 'path';

const ROOT = path.join(__dirname, '..', '..', '..');
const SW = path.join(ROOT, 'public', 'sw.js');

/**
 * The generator needs a real `next build` to read hashed filenames from, so
 * this reads whatever the last build produced rather than building here.
 * Skipped (not failed) when there's no build — a bare `npm test` on a fresh
 * clone shouldn't go red for that.
 */
const built = fs.existsSync(SW) && fs.readFileSync(SW, 'utf8').includes('GENERATED by scripts/build-sw.js');
const describeIfBuilt = built ? describe : describe.skip;

describeIfBuilt('generated service worker', () => {
  const sw = fs.readFileSync(SW, 'utf8');

  it('never caches the API', () => {
    // Learner state is per-account. A stale response is bad; a response
    // cached under one account and served to another is much worse. Progress
    // already lives in localStorage, so offline reads never need this.
    expect(sw).toMatch(/url\.pathname\.startsWith\('\/api\/'\)\)\s*return/);
  });

  it('only caches GET requests', () => {
    expect(sw).toMatch(/request\.method !== 'GET'\)\s*return/);
  });

  it('ignores cross-origin requests', () => {
    // OpenAI's realtime endpoint and the API live elsewhere; the worker has
    // no business touching either.
    expect(sw).toMatch(/url\.origin !== self\.location\.origin\)\s*return/);
  });

  it('cannot hang forever during install', () => {
    // The exact failure of the previous worker: install never resolved, so it
    // never activated and never controlled a page.
    expect(sw).toContain('fetchWithTimeout');
    expect(sw).toMatch(/AbortController/);
  });

  it('tolerates an individual precache miss', () => {
    // cache.addAll() rejects the whole batch on one failure; a missing icon
    // must never stop the worker activating. Matched on the CALL, not the
    // word — the generated worker's own comment mentions addAll to explain
    // why it isn't used.
    expect(sw).not.toMatch(/\.addAll\s*\(/);
    expect(sw).toMatch(/catch\s*\{/);
  });

  it('falls back to a real offline page rather than the browser error', () => {
    expect(sw).toContain("caches.match('/offline')");
  });

  it('serves pages network-first so a new build is never masked by the cache', () => {
    const navBlock = sw.slice(sw.indexOf("request.mode === 'navigate'"));
    // fetch() attempted before caches.match() in the navigation handler.
    expect(navBlock.indexOf('await fetch(request)')).toBeLessThan(navBlock.indexOf('caches.match(request)'));
  });

  it('drops caches from older versions on activate', () => {
    expect(sw).toMatch(/caches\.delete/);
  });
});

describe('service worker build script', () => {
  it('exists and is wired into the build', () => {
    expect(fs.existsSync(path.join(ROOT, 'scripts', 'build-sw.js'))).toBe(true);
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    expect(pkg.scripts.build).toContain('build-sw.js');
  });

  it('no longer depends on next-pwa', () => {
    // It generated the broken worker, and its last release was 2022.
    const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
    expect({ ...pkg.dependencies, ...pkg.devDependencies }['next-pwa']).toBeUndefined();
    expect(fs.readFileSync(path.join(ROOT, 'next.config.js'), 'utf8')).not.toContain('withPWA(');
  });
});

// Keeps `execFileSync` referenced for future use without tripping lint.
void execFileSync;
